import React, { useEffect, useState } from "react";
import Axios from "../Axios/Axios";
import { Table } from "react-bootstrap";

const ReportShowcase = () => {
    const [reports, setReports] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const response = await Axios.get("/reports/view_all/");
                console.log("API response:", response.data); // Debugging: Check the structure of response.data

                // Set reports only if response.data is an array, otherwise set to an empty array
                setReports(Array.isArray(response.data) ? response.data : []);
            } catch (error) {
                console.error("Failed to fetch reports:", error);
                setError("Failed to fetch reports");
            } finally {
                setLoading(false);
            }
        };

        fetchReports();
    }, []);

    if (loading) return <p>Loading reports...</p>;
    if (error) return <p>{error}</p>;

    return (
        <div className="report-showcase">
            <h3>Reports</h3>
            <Table striped bordered hover responsive>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Report Type</th>
                        <th>Generated By</th>
                        <th>Created At</th>
                        <th>Data</th>
                    </tr>
                </thead>
                <tbody>
                    {reports.length > 0 ? (
                        reports.map((report, index) => (
                            <tr key={index}>
                                <td>{index + 1}</td>
                                <td>{report.report_type}</td>
                                <td>{report.generated_by}</td>
                                <td>{new Date(report.created_at).toLocaleString()}</td>
                                <td>
                                    {report.report_type === "user_activity" ? (
                                        <>
                                            <p>User: {report.data.user}</p>
                                            <p>Total Tasks: {report.data.total_tasks}</p>
                                            <p>Completed Tasks: {report.data.completed_tasks}</p>
                                            <p>Overdue Tasks: {report.data.overdue_tasks}</p>
                                            <p>Completion: {report.data.completion_percentage}%</p>
                                        </>
                                    ) : report.report_type === "project_summary" ? (
                                        <>
                                            <p>Project: {report.data.project_name}</p>
                                            <p>Start Date: {report.data.start_date}</p>
                                            <p>End Date: {report.data.end_date}</p>
                                            <p>Total Tasks: {report.data.total_tasks}</p>
                                            <p>Completed: {report.data.completed_tasks}</p>
                                            <p>In Progress: {report.data.in_progress_tasks}</p>
                                            <p>Completion: {report.data.completion_percentage}%</p>
                                        </>
                                    ) : (
                                        <p>No data available</p>
                                    )}
                                </td>
                            </tr>
                        ))
                    ) : (
                        <tr>
                            <td colSpan="5">No reports available</td>
                        </tr>
                    )}
                </tbody>
            </Table>
        </div>
    );
};

export default ReportShowcase;

